services:
  - type: web
    name: Grid Guardian
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://superheros-6636.onrender.com
